use_frameworks!
inhibit_all_warnings!

# TODO: For local dev work
platform :ios, '11.0'

target 'AppLovin MAX Demo App - ObjC' do
  pod 'AppLovinSDK'
  # TODO: For local dev work
  pod 'Adjust'
  pod 'AppLovinMediationVerizonAdsAdapter', :path => '../VerizonAds'
end
